import {
  MOVIES,
  MOVIES_DETAIL,
  MOVIES_HIGHLIGHT,
  MOVIES_HIGHLIGHT_FAVOURITES,
  MOVIES_HIGHLIGHT_NEW,
  MOVIES_HIGHLIGHT_TRENDING,
} from "./movies";
import { USER } from "./users";

export const QUERY_USER = USER;
export const QUERY_MOVIES = MOVIES;
export const QUERY_MOVIES_DETAIL = MOVIES_DETAIL;
export const QUERY_MOVIES_HIGHLIGHT_FAVOURITES = MOVIES_HIGHLIGHT_FAVOURITES;
export const QUERY_MOVIES_HIGHLIGHT_TRENDING = MOVIES_HIGHLIGHT_TRENDING;
export const QUERY_MOVIES_HIGHLIGHT_NEW = MOVIES_HIGHLIGHT_NEW;
